### PR TITLE
Feature/create pip package

### PR DESCRIPTION
**Pull request by trejas**
In order to facilitate running of snowchange in CICD pipeline, I needed to create a pip installable version of the script. 

This pull request moved the main script into a package folder and created a `setup.py` file. 

I also published this version to pypi. I am happy to turn over the pypi name, but I definitely need to figure out how to install via pip before I transfer.

### CODE REVIEW

**Comment by jamesweakley** [comment]
Thanks for the PR @trejas , we're just reviewing another PR which will impact this one, but intend to accept this one

**Comment by jamesweakley** [comment]
Hi @trejas  we've finished merging that other PR now. Would you mind resolving the conflicting files? (should be very minor)

**Comment by jeremiahhansen** [comment]
Hey there @trejas, just wanted to follow-up on @jamesweakley question from [PR #8](https://github.com/jamesweakley/snowchange/pull/8). Can you please transfer the ownership of https://pypi.org/project/snowchange/ to James (his pypi username is jamesweakley)? Once that is done we can fine finalize the code changes and get snowchange out there as a pip package! Thanks.

**Comment by raphael-riel** [comment]
@jeremiahhansen Looks like you had no answer from @trejas. Have you tried the gmail address listed on his GH profile?
I would like to see this tool deployed as a pip-package, but I'm not willing to use a non-official one 😄

**Comment by jamesweakley** [comment]
I've contacted Traey and he's agreed to do this, I'll comment here again when it's done

**Comment by trejas** [comment]
Hi guys. Many apologies for the delay. I don't check my messages on github that often. I have sent an invite to add @jamesweakley as an owner of the pypi name. He should have it in his inbox now.

Also, please let me know if there are any modifications that need to be made to here. This pip package is in use at a customer, so please do not delete the deployed versions.

**Comment by RoyTrudell** [comment]
This is great! I can see its already available in pip.   Looking forward to this being mainlined.

**Review by RoyTrudell — APPROVED** [review]

**Review by RoyTrudell — COMMENTED** [review]
This is great! I can see its already available in pip.

Though, I've noticed the version I get from pip is fairly different from master branch and not useable for me.

Looking forward to the conflicts getting resolved and being mainlined.

**Comment by sfc-gh-jhansen** [comment]
Closing this PR as it's a duplicate of [PR #8](https://github.com/jamesweakley/snowchange/pull/8). That code has just been released and the package on PyPI has been updated!

**Pull request closed without merging**
